version: '3'
services:
  simulator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/home/weather-generator/output
    entrypoint: ["/bin/bash", "/home/weather-generator/run.sh", "${obs}"]

volumes:
  output: