version: '3'
services:
  simulator:
    build: .
    volumes:
      - ./output:/home/weather-generator/output
    entrypoint: ["/bin/bash", "/home/weather-generator/run.sh", "${obs}"]

volumes:
  output: